name: E2E Tests

on:
  pull_request:
    branches:
      - next
      - master

jobs:
  e2e_tests:
    runs-on: ubuntu-latest
    environment:
      name: development
    env:
      RESOLVER_DOMAIN: http://localhost:3000/api/1.0.0
      NODE_ENV: test
      OBJECT_STORAGE_ENDPOINT: localhost
      OBJECT_STORAGE_PORT: 9000
      OBJECT_STORAGE_USE_SSL: false
      OBJECT_STORAGE_ACCESS_KEY: minioadmin
      OBJECT_STORAGE_SECRET_KEY: minioadmin
      OBJECT_STORAGE_BUCKET_NAME: idr-bucket-test
      OBJECT_STORAGE_PATH_STYLE: true
      IDENTIFIER_PATH: identifiers
      API_KEY: test123
      APP_NAME: IDR
      LINK_TYPE_VOC_DOMAIN: http://localhost:3000/api/1.0.0/voc
      API_BASE_URL: http://localhost:3000

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js and Cache Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: "21" # install Node.js v21.x
          cache: npm
          cache-dependency-path: app/package-lock.json # cache dependencies for the app

      # Install dependencies for running E2E tests
      - name: Install dependencies
        run: npm ci
        working-directory: app

      - name: Start docker compose
        run: docker compose up -d # Start docker compose in the background

      # Run E2E tests and force exit after all tests have completed
      - name: Run E2E tests
        run: npm run test:e2e -- --forceExit
        working-directory: app

      - name: Stop docker compose
        run: docker compose down # Stop docker compose after all tests have completed
