name: Report Coverage
on:
  repository_dispatch:
    types: [coverage-report]

jobs:
  report:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      actions: read
      checks: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ github.event.client_payload.artifact_name }}
          path: coverage
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.client_payload.run_id }}

      - name: Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: coverage/report.json
          base-coverage-file: coverage/report.json
          threshold: 80
          prnumber: ${{ github.event.client_payload.pr_number }}
